force-app/main/default/objects/Aeropuerto__c/Aeropuerto__c.object-meta.xml
<CustomObject>
    <description>Es la locacion fisica que esta acondicionada para recibir y despachar vuelos de diferentes ciudades</description>
    <label>Aeropuerto</label>
    <nameField>
        <label>Nombre del Aeropuerto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeropuertos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clima__c/Clima__c.object-meta.xml
<CustomObject>
    <description>Es el registo de las condiciones climaticas para un aeropuesto en un momento determinado, esta informacion es guardada para cada vuelo 24 horas antes de ser realizado</description>
    <label>Clima</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Numero de Clima</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Climas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clima__c/fields/Aeropuerto__c.field-meta.xml
<CustomField>
    <fullName>Aeropuerto__c</fullName>
    <description>Aeropuerto del cual se consulta el clima</description>
    <label>Aeropuerto</label>
    <referenceTo>Aeropuerto__c</referenceTo>
    <relationshipLabel>Climas</relationshipLabel>
    <relationshipName>Climas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clima__c/fields/Fecha_y_Hora__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_Hora__c</fullName>
    <description>Fecha y hora en la que se realizo la consulta de clima</description>
    <label>Fecha y Hora de Prediccion</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Clima__c/fields/Temperatura__c.field-meta.xml
<CustomField>
    <fullName>Temperatura__c</fullName>
    <description>Temperatura atmosferica al momento de realizar la consulta</description>
    <label>Temperatura</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Clima__c/fields/Unidad__c.field-meta.xml
<CustomField>
    <fullName>Unidad__c</fullName>
    <description>Unidad en la que se ha realizado la consulta de le temperatura</description>
    <label>Unidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fahrenheit</fullName>
            </value>
            <value>
                <fullName>Centigrados</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchableEstadoVuelo.cls
public class BatchableEstadoVuelo implements Database.Batchable<sObject>, Database.AllowsCallouts {
    public Database.QueryLocator start(Database.BatchableContext BC){
        DateTime modificacionPasado = DateTime.now().addHours(-4);
        Datetime modificacionPresente = Datetime.now();
        return Database.getQueryLocator('select id, Estado__c, Fecha_y_hora_de_partida__c, Fecha_y_hora_estimada_de_llegada__c, Aeropuerto_de_llegada__r.Id, Aeropuerto_de_llegada__r.Ubicacion__Longitude__s,Aeropuerto_de_llegada__r.Ubicacion__Latitude__s from product2');
    }
    
    public void execute(Database.BatchableContext BC, List<Product2> vuelos){
        Datetime modificacion = Datetime.now();
        Set<Id> idVuelos = new Set<Id>();
        list<Product2> listaVuelos = new List<Product2>();
        List<clima__c> listaClimas = new List<clima__c>();
        try {
            for(product2 vuelo: vuelos){
                if(vuelo.Fecha_y_hora_de_partida__c <= modificacion && (vuelo.Estado__c == 'En Venta' || vuelo.Estado__c == 'Check In')){
                    string Latitud = string.valueOf(vuelo.Aeropuerto_de_llegada__r.Ubicacion__Latitude__s);
                    string Longitude = string.valueOf(vuelo.Aeropuerto_de_llegada__r.Ubicacion__Longitude__s);
                    Decimal Temperatura = ObtenerClima.getClima(Latitud, Longitude);
                    Clima__c clima = new Clima__c(Aeropuerto__c = vuelo.Aeropuerto_de_llegada__c,Fecha_y_Hora__c  = DateTime.now(),Unidad__c = 'Centigrados',Temperatura__c = Temperatura);
                    listaClimas.add(clima);
                    product2 vueloActualizado = new product2();
                    vueloActualizado.Id = vuelo.Id;
                    vueloActualizado.Estado__c = 'En Vuelo';
                    listaVuelos.add(vueloActualizado);
                }   
            }
            update listaVuelos;
            insert listaClimas;
        } catch (Exception e) {
            System.debug(e);
        }
        
    }
    
    public void finish(Database.BatchableContext BC){
        // notificar acerca del proceso
    }
}