force-app/main/default/objects/Aeropuerto__c/Aeropuerto__c.object-meta.xml
<CustomObject>
    <description>Es la locacion fisica que esta acondicionada para recibir y despachar vuelos de diferentes ciudades</description>
    <label>Aeropuerto</label>
    <nameField>
        <label>Nombre del Aeropuerto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeropuertos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aeropuerto__c/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <description>Ciudad perteneciente a un pais y seleccionable para un vuelo</description>
    <label>Ciudad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Pais__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Ciudad</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Aeropuerto__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <description>Listado de paises permitidos para un veulo</description>
    <label>Pais</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pais</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avion__c/Avion__c.object-meta.xml
<CustomObject>
    <description>es un artefacto de transporte de pasajeros o carga. Si el avión es de tipo carga no se debe admitir número de pasajeros</description>
    <label>Avion</label>
    <nameField>
        <displayFormat>AV{00000}</displayFormat>
        <label>Numero de Avion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aviones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avion__c/fields/Numero_de_pasajeros_clase_negocios__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_pasajeros_clase_negocios__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Numero de Asientos para la clase negocios</description>
    <label>Numero de pasajeros clase negocios</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/Numero_de_pasajeros_clase_turista__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_pasajeros_clase_turista__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Numero de asientos para la clase turista</description>
    <label>Numero de pasajeros clase turista</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Tipo de transporte al que pertenece el avion</description>
    <label>Tipo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/quitarDescuentoMartesTest.cls
@isTest
public class quitarDescuentoMartesTest {

    @testSetup
    static void makeData(){
        string pricebookId = Test.getStandardPricebookId();
        Pricebook2 standardPricebook = new Pricebook2(
            Id = pricebookId,
            IsActive = true
        );
        update standardPricebook;
        
        Pricebook2 turista = new Pricebook2(Name = 'Turista',IsActive = true);
        insert turista;
        
        Pricebook2 negocio = new Pricebook2(Name = 'Negocio',IsActive = true);
        insert negocio;
        
        Avion__c avion = new Avion__c (Numero_de_pasajeros_clase_negocios__c = 10,Numero_de_pasajeros_clase_turista__c = 10, Tipo__c ='pitovolador 1424');
        insert avion;
        
        list<Aeropuerto__c> aeropuertos = new List<Aeropuerto__c>();
        for(integer i = 0 ; i < 2; i++){
            Aeropuerto__c aeropuerto = new Aeropuerto__c(Name='aeropuerto'+i , Pais__c = 'Colombia', Ciudad__c = 'Antioquia');
            aeropuertos.add(aeropuerto);
        }
        insert aeropuertos;
        
        product2 vuelo = new product2(Name = 'ae56', Aeropuerto_de_partida__c =aeropuertos[0].id, Aeropuerto_de_llegada__c = aeropuertos[1].id,Estado__c = 'En Venta',IsActive = true,
                                      Fecha_y_hora_de_partida__c = Date.newInstance(2022, 08, 22),Avion__c = avion.Id,
                                      Fecha_y_hora_estimada_de_llegada__c = Date.newInstance(2022, 08, 23));
        insert vuelo;
        
        PricebookEntry entrada = new PricebookEntry(Pricebook2Id = pricebookId,UnitPrice=3250,Product2Id=vuelo.Id,IsActive = true, Descuento_Martes__c = true);
        insert entrada;
        
        PricebookEntry turisteando = new PricebookEntry(Pricebook2Id = turista.Id, UnitPrice=3250,Product2Id=vuelo.Id, IsActive = true, Descuento_Martes__c = true);
        insert turisteando;
    }
    
    @isTest
    private static void descuentoMartes(){
        Pricebook2 turista = [select id from Pricebook2 where Name = 'Turista' Limit 1];
        integer dia = Date.today().addDays(1).day();
        String conExpresion = '2022-08-'+dia +' 00:00:00';
        
        Test.startTest();
        detenerDescuentoMartes m = new detenerDescuentoMartes();
        String sch = '0 0 0 * * ? *';
        String jobID = system.schedule('Test Programado', sch, m);
        
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
                         	FROM CronTrigger WHERE id =: jobID];
        
        system.assertEquals(sch, ct.CronExpression);
        
        system.assertEquals(0, ct.TimesTriggered);
        
        system.assertEquals(conExpresion,String.valueOf(ct.NextFireTime));
        
        quitarDescuentoMartes batchClass = new quitarDescuentoMartes(); 
        ID batchprocessid = Database.executeBatch(batchClass) ;
        Test.stopTest();
        
        PricebookEntry precio = [Select UnitPrice from PricebookEntry Where Pricebook2Id =: turista.Id Limit 1];
        system.assertEquals(5000, precio.UnitPrice);
    }
}