force-app/main/default/objects/Aeropuerto__c/Aeropuerto__c.object-meta.xml
<CustomObject>
    <description>Es la locacion fisica que esta acondicionada para recibir y despachar vuelos de diferentes ciudades</description>
    <label>Aeropuerto</label>
    <nameField>
        <label>Nombre del Aeropuerto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeropuertos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aeropuerto__c/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <description>Ciudad perteneciente a un pais y seleccionable para un vuelo</description>
    <label>Ciudad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Pais__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Ciudad</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Aeropuerto__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <description>Listado de paises permitidos para un veulo</description>
    <label>Pais</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pais</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avion__c/Avion__c.object-meta.xml
<CustomObject>
    <description>es un artefacto de transporte de pasajeros o carga. Si el avión es de tipo carga no se debe admitir número de pasajeros</description>
    <label>Avion</label>
    <nameField>
        <displayFormat>AV{00000}</displayFormat>
        <label>Numero de Avion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aviones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avion__c/fields/Numero_de_pasajeros_clase_negocios__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_pasajeros_clase_negocios__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Numero de Asientos para la clase negocios</description>
    <label>Numero de pasajeros clase negocios</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/Numero_de_pasajeros_clase_turista__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_pasajeros_clase_turista__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Numero de asientos para la clase turista</description>
    <label>Numero de pasajeros clase turista</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Tipo de transporte al que pertenece el avion</description>
    <label>Tipo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Clima__c/Clima__c.object-meta.xml
<CustomObject>
    <description>Es el registo de las condiciones climaticas para un aeropuesto en un momento determinado, esta informacion es guardada para cada vuelo 24 horas antes de ser realizado</description>
    <label>Clima</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Numero de Clima</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Climas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clima__c/fields/Aeropuerto__c.field-meta.xml
<CustomField>
    <fullName>Aeropuerto__c</fullName>
    <description>Aeropuerto del cual se consulta el clima</description>
    <label>Aeropuerto</label>
    <referenceTo>Aeropuerto__c</referenceTo>
    <relationshipLabel>Climas</relationshipLabel>
    <relationshipName>Climas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SchedulableCadaDiaTest.cls
@isTest
public class SchedulableCadaDiaTest {
    
    @testSetup
    static void makeData(){
        string pricebookId = Test.getStandardPricebookId();
        Pricebook2 standardPricebook = new Pricebook2(
            Id = pricebookId,
            IsActive = true
        );
        update standardPricebook;
        
        Pricebook2 turista = new Pricebook2(Name = 'Turista',IsActive = true);
        insert turista;
        
        Pricebook2 negocio = new Pricebook2(Name = 'Negocio',IsActive = true);
        insert negocio;
        
        Avion__c avion = new Avion__c (Numero_de_pasajeros_clase_negocios__c = 10,Numero_de_pasajeros_clase_turista__c = 10, Tipo__c ='pitovolador 1424');
        insert avion;
        
        list<Aeropuerto__c> aeropuertos = new List<Aeropuerto__c>();
        for(integer i = 0 ; i < 2; i++){
            Aeropuerto__c aeropuerto = new Aeropuerto__c(Name='aeropuerto'+i , Pais__c = 'Colombia', Ciudad__c = 'Antioquia', Ubicacion__latitude__s = 	6.243499 ,Ubicacion__longitude__s =	-75.579226 );
            aeropuertos.add(aeropuerto);
        }
        insert aeropuertos;
        
        list<product2> vuelos = new List<Product2>();
        for(integer i = 0 ; i<15; i++){
            if(i <10){
                Date fechaPartida = date.today().addDays(1);
                Date fechaLlegada = date.today().addDays(2); 
                product2 vuelo = new product2(Name = 'ae56'+i, Aeropuerto_de_partida__c =aeropuertos[0].id, Aeropuerto_de_llegada__c = aeropuertos[1].id,Estado__c = 'En Venta',IsActive = true,
                                              Fecha_y_hora_de_partida__c = fechaPartida ,Avion__c = avion.Id,Fecha_y_hora_estimada_de_llegada__c = fechaLlegada);
                vuelos.add(vuelo);
            }else{
                Date fechaPartida = date.today().addDays(5);
                Date fechaLlegada = date.today().addDays(6); 
                product2 vuelo = new product2(Name = 'ae56'+i, Aeropuerto_de_partida__c =aeropuertos[0].id, Aeropuerto_de_llegada__c = aeropuertos[1].id,Estado__c = 'En Venta',IsActive = true,
                                              Fecha_y_hora_de_partida__c = fechaPartida ,Avion__c = avion.Id,Fecha_y_hora_estimada_de_llegada__c = fechaLlegada);
                vuelos.add(vuelo);
            }
            
        }
        insert vuelos;
        
        list<pricebookEntry> EntradaListaPreciosEstandar = new List<PricebookEntry>();
        list<pricebookEntry> EntradaListaPreciosTuristaYNegocio = new List<PricebookEntry>();
        for(product2 vuelo: vuelos){
            pricebookEntry precioestandard = new PricebookEntry(isActive = true, Pricebook2Id = pricebookId, unitprice = 100, product2Id = vuelo.Id );
            EntradaListaPreciosEstandar.add(precioestandard);
            
            pricebookEntry precioTurista = new PricebookEntry(isActive = true, Pricebook2Id = turista.Id, unitprice = 100, product2Id = vuelo.Id );
            pricebookEntry precioNegocio = new PricebookEntry(isActive = true, Pricebook2Id = negocio.Id, unitprice = 100, product2Id = vuelo.Id ,	Descuento_Martes__c = true);
            
            EntradaListaPreciosTuristaYNegocio.add(precioTurista);
            EntradaListaPreciosTuristaYNegocio.add(precioNegocio);
        }
        insert EntradaListaPreciosEstandar;
        insert EntradaListaPreciosTuristaYNegocio;
    }
    
    @isTest
    static void programarCadaDia(){
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('GetClimaResource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        Test.setMock(HttpCalloutMock.class, mock);
        
        SchedulableCadaDia m = new SchedulableCadaDia();
        String sch = '0 0 * * * ?'; 
        
        Test.startTest();
        
        String jobID = system.schedule('Schedulable (cada dia) TEST', sch, m);
        
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
                          NextFireTime
                          FROM CronTrigger WHERE id = :jobId];
        
        DateTime actual = datetime.now().addhours(1);
        
        System.assertEquals(sch, ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);
        
        FutureDiaAntes.validarVuelos();
        
        Test.stopTest();
        
        //CronTrigger cronTrigger_after = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobId];
		//System.assertEquals(1, cronTrigger_after.TimesTriggered);
        
        List<Product2> vuelosARevisar = [select id, Estado__c from Product2 where Estado__c = 'check In'];
        system.assertEquals(10, vuelosARevisar.size());
        
        List<Clima__c> climas = [select id from Clima__c];
        system.assertEquals(10, climas.size());
        
        List<PricebookEntry> precios = [select id from PricebookEntry where Descuento_Por_Vencer__c = true];
        system.assertEquals(30, precios.size());
    }
}