force-app/main/default/objects/Avion__c/Avion__c.object-meta.xml
<CustomObject>
    <description>es un artefacto de transporte de pasajeros o carga. Si el avión es de tipo carga no se debe admitir número de pasajeros</description>
    <label>Avion</label>
    <nameField>
        <displayFormat>AV{00000}</displayFormat>
        <label>Numero de Avion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aviones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avion__c/fields/Numero_de_pasajeros_clase_negocios__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_pasajeros_clase_negocios__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Numero de Asientos para la clase negocios</description>
    <label>Numero de pasajeros clase negocios</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/Numero_de_pasajeros_clase_turista__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_pasajeros_clase_turista__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Numero de asientos para la clase turista</description>
    <label>Numero de pasajeros clase turista</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Tipo de transporte al que pertenece el avion</description>
    <label>Tipo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VueloX__c/VueloX__c.object-meta.xml
<CustomObject>
    <description>Juction para relacion many to many entre vuelo y contacto</description>
    <label>Auxiliar de Vuelo</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Numero de Vuelo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auxiliares de Vuelo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VueloX__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Auxiliar de Vuelo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>VueloxContactos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VueloX__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>VueloxContactos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TripulacionRequeridaTest.cls
@isTest
public with sharing class TripulacionRequeridaTest {
   
    @TestSetup
    static void makeData(){
        avion__c avion = new avion__c(	Numero_de_pasajeros_clase_negocios__c=0,Numero_de_pasajeros_clase_turista__c=150,Tipo__c='superMegaVoladoraMaquina');

        insert avion;
        avion__c avionsito = [SELECT Id FROM Avion__c LIMIT 1];

        product2 vuelo = new Product2(Name = 'AV-0001', Avion__c = avionsito.Id , Fecha_y_hora_de_partida__c = DateTime.now()+8/7,
                                    Fecha_y_hora_estimada_de_llegada__c = (DateTime.now()+8/7).addHours(1), IsActive = true, Estado__c = 'En Venta');

        insert vuelo;

        Contact auxiliar = new Contact(firstName='josefino', lastName='pan y vino', RecordTypeId='0128a0000017rhWAAQ',
                                        Numero_de_pasaporte__c='12312345',Nacionalidad__c='colombiano',
                                        ffecha_de_nacimiento__c=Date.newInstance(1999,05,09));

        insert auxiliar;

        List<Contact> contactito = new List<Contact>();
        for(integer i = 0; i < 1;i++){
            Contact auxiliar1 = new Contact(firstName='josefino'+i, lastName='pan y vino'+i, RecordTypeId='0128a0000017rhWAAQ',
                                        Numero_de_pasaporte__c='1231234522+i',Nacionalidad__c='argentino',
                                        ffecha_de_nacimiento__c=Date.newInstance(1999,05,09));
            contactito.add(auxiliar1);
        }
        
        insert contactito;

        product2 vuelito = [SELECT Id from Product2 LIMIT 1];
        Contact auxiliarsito = [SELECT Id FROM Contact LIMIT 1];

        VueloX__c junction = new VueloX__c(Contact__c = auxiliarsito.Id,Product__c = vuelito.Id);
        insert junction;
        
    }

    @isTest
    private static void obtienenUnVuelo(){
        List<TripulacionRequerida.vuelo> vuelos = TripulacionRequerida.obtenerVuelos();
        system.assertEquals(1, vuelos.size());
    }

    @isTest
    private static void errorObtienenUnVuelo(){
        avion__c avionsin = [SELECT Id FROM avion__c LIMIT 1];
        delete avionsin;
        
        try {
            List<TripulacionRequerida.vuelo> vuelos = TripulacionRequerida.obtenerVuelos();
        }
        catch (Exception e) {
            system.assert(e.getMessage().contains('Script-thrown exception'));
        }
        
    }

    @isTest
    private static void auxiliares(){
        
        Product2 vuelos = [SELECT Id FROM product2 LIMIT 1];
        
        List<TripulacionRequerida.opcion> auxiliares = TripulacionRequerida.getAuxiliares(vuelos.id);
        system.assertEquals(3, auxiliares.size());
        
    }
    // Validar el metodo getAuxiliares con error
    @isTest
    private static void auxiliaresConError(){
        
        List<TripulacionRequerida.opcion> auxiliares = TripulacionRequerida.getAuxiliares('1231sdd');
        
    }

    @isTest
    private static void guardarAuxiliares(){
        Product2 vuelos = [SELECT Id FROM product2 LIMIT 1];
        
        

        List<Contact> obtenidoAuxiliar = [SELECT Id FROM Contact];
        List<string> ids = new List<string>();
        for(Contact a: obtenidoAuxiliar){
            ids.add(a.Id);
        }
        

        TripulacionRequerida.saveAuxiliares(ids,vuelos.id);

        List<TripulacionRequerida.opcion> auxiliares = TripulacionRequerida.getAuxiliares(vuelos.id);
        system.assertEquals(4, auxiliares.size());
    }
}